### PR TITLE
small changes for OS X compatibility

### PR DESCRIPTION
**Pull request by mredig**

### CODE REVIEW

**Comment by mredig** [comment]
Okay, whitespace gone.

**Comment by hellozimi** [comment]
Fair enough, was just curious :)! Thanks for fixing the whitespace and the osx patch.

**Comment by mredig** [comment]
Hey, if there's a better way, I'm all for it! I definitely don't know it all!

**Comment by hellozimi** [comment]
I would say both ways is ok. `#define` is a macro which is a preprocessor token and typedef creates a real defined type. If Apple uses `#define` I'm all for it. 

If you're interested I found [this](http://stackoverflow.com/a/1666375/356338) a good example how they differ.

Thanks for your patch!

**Pull request merged**
